### 조건에 맞는 데이터만 검색(필터링)
- df.query('조건식')  # 조건식은 스트링으로
- df.query("조건식")
- df.query('math >= 60')
- 비교연산자:
    - ==, !=, >, >=, <, <=
- 논리연산자:
    - and, or, not
- 비트연산자:
    - &, |, ~
- 포함연산자:
    - in, not in

In [1]:
import pandas as pd
df = pd.read_csv('exam.csv', header=0)
print(df)

    no  nclass  hours  extra  math  eng  science  tot  test
0   11       1     17      6    37   70       44  151  Pass
1   12       1     30      7    60   80       70  210  Pass
2   13       1     19      7    41   71       46  158  Pass
3   14       1     14      4    34   67       40  141  Fail
4   15       1     27      4    82   78       73  233  Pass
5   21       2     13      4    34   67       38  139  Fail
6   22       2     35      9    84   83       85  252  Pass
7   23       2     21      7    45   70       49  164  Pass
8   24       2     16      8    34   69       42  145  Fail
9   25       2     31      8    43   69       45  157  Fail
10  31       3     10      1    35   65       36  136  Fail
11  32       3     15      8    35   68       41  144  Fail
12  33       3     23      5    46   71       55  172  Pass
13  34       3     11      5    34   66       37  137  Fail
14  35       3     29      7    58   80       68  206  Pass
15  41       4     25      5    49   75       59  183  Pass
16  42       4      9      2    33   67       35  135  Fail
17  43       4     24      6    48   74       58  180  Pass
18  44       4     33      8    81   80       80  241  Pass
19  45       4     38      8    83   78       97  258  Pass
20  51       5     40      9    85   86       90  261  Pass
21  52       5     39     10    87   85       87  259  Pass
22  53       5     32      7    76   82       78  236  Pass
23  54       5     27      5    51   78       60  189  Pass
24  55       5     32      6    44   67       50  161  Fail

In [4]:
df1 = df.query('nclass==1') # 1반인 경우 추출
print(df1)

   no  nclass  hours  extra  math  eng  science  tot  test
0  11       1     17      6    37   70       44  151  Pass
1  12       1     30      7    60   80       70  210  Pass
2  13       1     19      7    41   71       46  158  Pass
3  14       1     14      4    34   67       40  141  Fail
4  15       1     27      4    82   78       73  233  Pass

In [3]:
df1 = df.query('nclass!=1') # 1반이 아닌 경우 추출
print(df1)

    no  nclass  hours  extra  math  eng  science  tot  test
5   21       2     13      4    34   67       38  139  Fail
6   22       2     35      9    84   83       85  252  Pass
7   23       2     21      7    45   70       49  164  Pass
8   24       2     16      8    34   69       42  145  Fail
9   25       2     31      8    43   69       45  157  Fail
10  31       3     10      1    35   65       36  136  Fail
11  32       3     15      8    35   68       41  144  Fail
12  33       3     23      5    46   71       55  172  Pass
13  34       3     11      5    34   66       37  137  Fail
14  35       3     29      7    58   80       68  206  Pass
15  41       4     25      5    49   75       59  183  Pass
16  42       4      9      2    33   67       35  135  Fail
17  43       4     24      6    48   74       58  180  Pass
18  44       4     33      8    81   80       80  241  Pass
19  45       4     38      8    83   78       97  258  Pass
20  51       5     40      9    85   86       90  261  Pass
21  52       5     39     10    87   85       87  259  Pass
22  53       5     32      7    76   82       78  236  Pass
23  54       5     27      5    51   78       60  189  Pass
24  55       5     32      6    44   67       50  161  Fail

In [5]:
df1 = df.query('math>80 and nclass!=1') # 수학 점수가 80점 이상이고 1반이 아닌 경우 추출
print(df1)

    no  nclass  hours  extra  math  eng  science  tot  test
6   22       2     35      9    84   83       85  252  Pass
18  44       4     33      8    81   80       80  241  Pass
19  45       4     38      8    83   78       97  258  Pass
20  51       5     40      9    85   86       90  261  Pass
21  52       5     39     10    87   85       87  259  Pass

In [ ]:
# 영어 점수가 50점 이상이고 수학 점수가 50점 이상이며 1반인 경우 추출
df1 = df.query('eng>=50 and math>=50 and nclass==1')
print(df1)

   no  nclass  hours  extra  math  eng  science  tot  test
1  12       1     30      7    60   80       70  210  Pass
4  15       1     27      4    82   78       73  233  Pass

In [8]:
# 1반, 3반, 5반인 경우 추출
df1 = df.query('nclass==1 or nclass==3 or nclass==5')
print(df1)

    no  nclass  hours  extra  math  eng  science  tot  test
0   11       1     17      6    37   70       44  151  Pass
1   12       1     30      7    60   80       70  210  Pass
2   13       1     19      7    41   71       46  158  Pass
3   14       1     14      4    34   67       40  141  Fail
4   15       1     27      4    82   78       73  233  Pass
10  31       3     10      1    35   65       36  136  Fail
11  32       3     15      8    35   68       41  144  Fail
12  33       3     23      5    46   71       55  172  Pass
13  34       3     11      5    34   66       37  137  Fail
14  35       3     29      7    58   80       68  206  Pass
20  51       5     40      9    85   86       90  261  Pass
21  52       5     39     10    87   85       87  259  Pass
22  53       5     32      7    76   82       78  236  Pass
23  54       5     27      5    51   78       60  189  Pass
24  55       5     32      6    44   67       50  161  Fail

in 사용하기

In [11]:
df1 = df.query('nclass in [1, 3, 5]')
print(df1)
df1 = df.query('nclass not in [1, 3, 5]')
print(df1)

    no  nclass  hours  extra  math  eng  science  tot  test
0   11       1     17      6    37   70       44  151  Pass
1   12       1     30      7    60   80       70  210  Pass
2   13       1     19      7    41   71       46  158  Pass
3   14       1     14      4    34   67       40  141  Fail
4   15       1     27      4    82   78       73  233  Pass
10  31       3     10      1    35   65       36  136  Fail
11  32       3     15      8    35   68       41  144  Fail
12  33       3     23      5    46   71       55  172  Pass
13  34       3     11      5    34   66       37  137  Fail
14  35       3     29      7    58   80       68  206  Pass
20  51       5     40      9    85   86       90  261  Pass
21  52       5     39     10    87   85       87  259  Pass
22  53       5     32      7    76   82       78  236  Pass
23  54       5     27      5    51   78       60  189  Pass
24  55       5     32      6    44   67       50  161  Fail
    no  nclass  hours  extra  math  eng  science  tot  test
5   21       2     13      4    34   67       38  139  Fail
6   22       2     35      9    84   83       85  252  Pass
7   23       2     21      7    45   70       49  164  Pass
8   24       2     16      8    34   69       42  145  Fail
9   25       2     31      8    43   69       45  157  Fail
15  41       4     25      5    49   75       59  183  Pass
16  42       4      9      2    33   67       35  135  Fail
17  43       4     24      6    48   74       58  180  Pass
18  44       4     33      8    81   80       80  241  Pass
19  45       4     38      8    83   78       97  258  Pass

In [ ]:
# 1반이면서 test가 Pass인 경우 추출
df1 = df.query('nclass ==1 and test == "Pass"')
df1

   no  nclass  hours  extra  math  eng  science  tot  test
0  11       1     17      6    37   70       44  151  Pass
1  12       1     30      7    60   80       70  210  Pass
2  13       1     19      7    41   71       46  158  Pass
4  15       1     27      4    82   78       73  233  Pass

In [ ]:
# f-string 사용하기
num = 1
df1 = df.query(f'nclass == {num} and test == "Pass"')
df1

   no  nclass  hours  extra  math  eng  science  tot  test
0  11       1     17      6    37   70       44  151  Pass
1  12       1     30      7    60   80       70  210  Pass
2  13       1     19      7    41   71       46  158  Pass
4  15       1     27      4    82   78       73  233  Pass

In [15]:
# @ 사용해서 변수 입력하기
var1 = 1
var2 = "Pass"
df1 = df.query('nclass == @var1 and test == @var2')
df1

   no  nclass  hours  extra  math  eng  science  tot  test
0  11       1     17      6    37   70       44  151  Pass
1  12       1     30      7    60   80       70  210  Pass
2  13       1     19      7    41   71       46  158  Pass
4  15       1     27      4    82   78       73  233  Pass

1. 데이터프레임(DataFrame), 필요한 컬럼만 추출(분리)
- 데이터프레임명['컬럼명'] # 1차원, 시리즈(Series)
- 데이터프레임명[['컬럼명', '컬럼명']] # 2차원, 데이터프레임

2. 컬럼 제거, 삭제(나머지 컬럼)
- 데이터프레임명.drop(columns='tot')
- 데이터프레임명.drop('tot', axis=1)

In [2]:
import pandas as pd
df = pd.read_csv('exam.csv', header=0)
print(type(df))

<class 'pandas.DataFrame'>

In [6]:
print(df['math']) # 1차원, 시리즈(Series)
# print("-" * 50)
# print(df[['math']]) # 2차원, 데이터프레임

0     37
1     60
2     41
3     34
4     82
5     34
6     84
7     45
8     34
9     43
10    35
11    35
12    46
13    34
14    58
15    49
16    33
17    48
18    81
19    83
20    85
21    87
22    76
23    51
24    44
Name: math, dtype: int64

In [ ]:
df[['no', 'nclass']] # 2차원, 데이터프레임

    no  nclass
0   11       1
1   12       1
2   13       1
3   14       1
4   15       1
5   21       2
6   22       2
7   23       2
8   24       2
9   25       2
10  31       3
11  32       3
12  33       3
13  34       3
14  35       3
15  41       4
16  42       4
17  43       4
18  44       4
19  45       4
20  51       5
21  52       5
22  53       5
23  54       5
24  55       5

In [10]:
print(df.drop(columns=['no', 'nclass'])) # no, nclass 컬럼 제거

    hours  extra  math  eng  science  tot  test
0      17      6    37   70       44  151  Pass
1      30      7    60   80       70  210  Pass
2      19      7    41   71       46  158  Pass
3      14      4    34   67       40  141  Fail
4      27      4    82   78       73  233  Pass
5      13      4    34   67       38  139  Fail
6      35      9    84   83       85  252  Pass
7      21      7    45   70       49  164  Pass
8      16      8    34   69       42  145  Fail
9      31      8    43   69       45  157  Fail
10     10      1    35   65       36  136  Fail
11     15      8    35   68       41  144  Fail
12     23      5    46   71       55  172  Pass
13     11      5    34   66       37  137  Fail
14     29      7    58   80       68  206  Pass
15     25      5    49   75       59  183  Pass
16      9      2    33   67       35  135  Fail
17     24      6    48   74       58  180  Pass
18     33      8    81   80       80  241  Pass
19     38      8    83   78       97  258  Pass
20     40      9    85   86       90  261  Pass
21     39     10    87   85       87  259  Pass
22     32      7    76   82       78  236  Pass
23     27      5    51   78       60  189  Pass
24     32      6    44   67       50  161  Fail

In [11]:
print(df.drop(['no', 'nclass'], axis=1)) # no, nclass

    hours  extra  math  eng  science  tot  test
0      17      6    37   70       44  151  Pass
1      30      7    60   80       70  210  Pass
2      19      7    41   71       46  158  Pass
3      14      4    34   67       40  141  Fail
4      27      4    82   78       73  233  Pass
5      13      4    34   67       38  139  Fail
6      35      9    84   83       85  252  Pass
7      21      7    45   70       49  164  Pass
8      16      8    34   69       42  145  Fail
9      31      8    43   69       45  157  Fail
10     10      1    35   65       36  136  Fail
11     15      8    35   68       41  144  Fail
12     23      5    46   71       55  172  Pass
13     11      5    34   66       37  137  Fail
14     29      7    58   80       68  206  Pass
15     25      5    49   75       59  183  Pass
16      9      2    33   67       35  135  Fail
17     24      6    48   74       58  180  Pass
18     33      8    81   80       80  241  Pass
19     38      8    83   78       97  258  Pass
20     40      9    85   86       90  261  Pass
21     39     10    87   85       87  259  Pass
22     32      7    76   82       78  236  Pass
23     27      5    51   78       60  189  Pass
24     32      6    44   67       50  161  Fail

1. 정렬(sort) 하기 : 특정 컬럼을 기준
- df.sort_values('컬럼명', ascending=True) # 오름차순(ascending)
- df.sort_values('컬럼명') # 오름차순(기본값)
    - 10 20 30 40

- df.sort_values('컬럼명', ascending=False) # 내림차순(descending)
    -40 30 20 10

2. 정렬을 위한 컬럼이 여러개인 경우
- df.sort_values( ['컬럼명1', '컬럼명2'] )
- df.sort_values( ['컬럼명1', '컬럼명2'], ascending=[True, False] )

In [12]:
import pandas as pd
df = pd.read_csv('exam.csv', header=0)
print(df)

    no  nclass  hours  extra  math  eng  science  tot  test
0   11       1     17      6    37   70       44  151  Pass
1   12       1     30      7    60   80       70  210  Pass
2   13       1     19      7    41   71       46  158  Pass
3   14       1     14      4    34   67       40  141  Fail
4   15       1     27      4    82   78       73  233  Pass
5   21       2     13      4    34   67       38  139  Fail
6   22       2     35      9    84   83       85  252  Pass
7   23       2     21      7    45   70       49  164  Pass
8   24       2     16      8    34   69       42  145  Fail
9   25       2     31      8    43   69       45  157  Fail
10  31       3     10      1    35   65       36  136  Fail
11  32       3     15      8    35   68       41  144  Fail
12  33       3     23      5    46   71       55  172  Pass
13  34       3     11      5    34   66       37  137  Fail
14  35       3     29      7    58   80       68  206  Pass
15  41       4     25      5    49   75       59  183  Pass
16  42       4      9      2    33   67       35  135  Fail
17  43       4     24      6    48   74       58  180  Pass
18  44       4     33      8    81   80       80  241  Pass
19  45       4     38      8    83   78       97  258  Pass
20  51       5     40      9    85   86       90  261  Pass
21  52       5     39     10    87   85       87  259  Pass
22  53       5     32      7    76   82       78  236  Pass
23  54       5     27      5    51   78       60  189  Pass
24  55       5     32      6    44   67       50  161  Fail

In [14]:
# 전교 석차 구하기 
sort_tot = df.sort_values('tot', ascending=False) # tot 컬럼을 기준으로 내림차순 정렬
print(sort_tot.head(3)) # 상위 3개 행 출력

    no  nclass  hours  extra  math  eng  science  tot  test
20  51       5     40      9    85   86       90  261  Pass
21  52       5     39     10    87   85       87  259  Pass
19  45       4     38      8    83   78       97  258  Pass

In [15]:
# 반별로 석차 구하기
sort_tot = df.sort_values(['nclass', 'tot'], ascending=[True, False])
sort_tot

    no  nclass  hours  extra  math  eng  science  tot  test
4   15       1     27      4    82   78       73  233  Pass
1   12       1     30      7    60   80       70  210  Pass
2   13       1     19      7    41   71       46  158  Pass
0   11       1     17      6    37   70       44  151  Pass
3   14       1     14      4    34   67       40  141  Fail
6   22       2     35      9    84   83       85  252  Pass
7   23       2     21      7    45   70       49  164  Pass
9   25       2     31      8    43   69       45  157  Fail
8   24       2     16      8    34   69       42  145  Fail
5   21       2     13      4    34   67       38  139  Fail
14  35       3     29      7    58   80       68  206  Pass
12  33       3     23      5    46   71       55  172  Pass
11  32       3     15      8    35   68       41  144  Fail
13  34       3     11      5    34   66       37  137  Fail
10  31       3     10      1    35   65       36  136  Fail
19  45       4     38      8    83   78       97  258  Pass
18  44       4     33      8    81   80       80  241  Pass
15  41       4     25      5    49   75       59  183  Pass
17  43       4     24      6    48   74       58  180  Pass
16  42       4      9      2    33   67       35  135  Fail
20  51       5     40      9    85   86       90  261  Pass
21  52       5     39     10    87   85       87  259  Pass
22  53       5     32      7    76   82       78  236  Pass
23  54       5     27      5    51   78       60  189  Pass
24  55       5     32      6    44   67       50  161  Fail

### 새로운 컬럼 추가하기
- 파생 컬럼(변수) 추가하기 
    - df['avg'] = df['tot'] / 3
- assign() 함수(C5블록)
    - df = df.assign(avg = df['tot'] / 3)
    - df = df.assign(avg = df['tot'] / 3, me_avg = (df['math']+df['eng'])/2)
    - df = df.assign(retest = np.where(df['avg'] >= 60, 'No', 'Ok'))

In [2]:
import pandas as pd
df = pd.read_csv('exam.csv', header=0)
df['avg'] = df['tot'] / 3
print(df)

    no  nclass  hours  extra  math  eng  science  tot  test        avg
0   11       1     17      6    37   70       44  151  Pass  50.333333
1   12       1     30      7    60   80       70  210  Pass  70.000000
2   13       1     19      7    41   71       46  158  Pass  52.666667
3   14       1     14      4    34   67       40  141  Fail  47.000000
4   15       1     27      4    82   78       73  233  Pass  77.666667
5   21       2     13      4    34   67       38  139  Fail  46.333333
6   22       2     35      9    84   83       85  252  Pass  84.000000
7   23       2     21      7    45   70       49  164  Pass  54.666667
8   24       2     16      8    34   69       42  145  Fail  48.333333
9   25       2     31      8    43   69       45  157  Fail  52.333333
10  31       3     10      1    35   65       36  136  Fail  45.333333
11  32       3     15      8    35   68       41  144  Fail  48.000000
12  33       3     23      5    46   71       55  172  Pass  57.333333
13  34       3     11      5    34   66       37  137  Fail  45.666667
14  35       3     29      7    58   80       68  206  Pass  68.666667
15  41       4     25      5    49   75       59  183  Pass  61.000000
16  42       4      9      2    33   67       35  135  Fail  45.000000
17  43       4     24      6    48   74       58  180  Pass  60.000000
18  44       4     33      8    81   80       80  241  Pass  80.333333
19  45       4     38      8    83   78       97  258  Pass  86.000000
20  51       5     40      9    85   86       90  261  Pass  87.000000
21  52       5     39     10    87   85       87  259  Pass  86.333333
22  53       5     32      7    76   82       78  236  Pass  78.666667
23  54       5     27      5    51   78       60  189  Pass  63.000000
24  55       5     32      6    44   67       50  161  Fail  53.666667

In [3]:
df = df.assign(avg = df['tot'] / 3)
print(df)

    no  nclass  hours  extra  math  eng  science  tot  test        avg
0   11       1     17      6    37   70       44  151  Pass  50.333333
1   12       1     30      7    60   80       70  210  Pass  70.000000
2   13       1     19      7    41   71       46  158  Pass  52.666667
3   14       1     14      4    34   67       40  141  Fail  47.000000
4   15       1     27      4    82   78       73  233  Pass  77.666667
5   21       2     13      4    34   67       38  139  Fail  46.333333
6   22       2     35      9    84   83       85  252  Pass  84.000000
7   23       2     21      7    45   70       49  164  Pass  54.666667
8   24       2     16      8    34   69       42  145  Fail  48.333333
9   25       2     31      8    43   69       45  157  Fail  52.333333
10  31       3     10      1    35   65       36  136  Fail  45.333333
11  32       3     15      8    35   68       41  144  Fail  48.000000
12  33       3     23      5    46   71       55  172  Pass  57.333333
13  34       3     11      5    34   66       37  137  Fail  45.666667
14  35       3     29      7    58   80       68  206  Pass  68.666667
15  41       4     25      5    49   75       59  183  Pass  61.000000
16  42       4      9      2    33   67       35  135  Fail  45.000000
17  43       4     24      6    48   74       58  180  Pass  60.000000
18  44       4     33      8    81   80       80  241  Pass  80.333333
19  45       4     38      8    83   78       97  258  Pass  86.000000
20  51       5     40      9    85   86       90  261  Pass  87.000000
21  52       5     39     10    87   85       87  259  Pass  86.333333
22  53       5     32      7    76   82       78  236  Pass  78.666667
23  54       5     27      5    51   78       60  189  Pass  63.000000
24  55       5     32      6    44   67       50  161  Fail  53.666667

In [4]:
# 여러 개의 컬럼을 한 번에 추가하기
df = df.assign(avg = df['tot'] / 3, me_avg = (df['math']+df['eng'])/2)
print(df)

    no  nclass  hours  extra  math  eng  science  tot  test        avg  me_avg
0   11       1     17      6    37   70       44  151  Pass  50.333333    53.5
1   12       1     30      7    60   80       70  210  Pass  70.000000    70.0
2   13       1     19      7    41   71       46  158  Pass  52.666667    56.0
3   14       1     14      4    34   67       40  141  Fail  47.000000    50.5
4   15       1     27      4    82   78       73  233  Pass  77.666667    80.0
5   21       2     13      4    34   67       38  139  Fail  46.333333    50.5
6   22       2     35      9    84   83       85  252  Pass  84.000000    83.5
7   23       2     21      7    45   70       49  164  Pass  54.666667    57.5
8   24       2     16      8    34   69       42  145  Fail  48.333333    51.5
9   25       2     31      8    43   69       45  157  Fail  52.333333    56.0
10  31       3     10      1    35   65       36  136  Fail  45.333333    50.0
11  32       3     15      8    35   68       41  144  Fail  48.000000    51.5
12  33       3     23      5    46   71       55  172  Pass  57.333333    58.5
13  34       3     11      5    34   66       37  137  Fail  45.666667    50.0
14  35       3     29      7    58   80       68  206  Pass  68.666667    69.0
15  41       4     25      5    49   75       59  183  Pass  61.000000    62.0
16  42       4      9      2    33   67       35  135  Fail  45.000000    50.0
17  43       4     24      6    48   74       58  180  Pass  60.000000    61.0
18  44       4     33      8    81   80       80  241  Pass  80.333333    80.5
19  45       4     38      8    83   78       97  258  Pass  86.000000    80.5
20  51       5     40      9    85   86       90  261  Pass  87.000000    85.5
21  52       5     39     10    87   85       87  259  Pass  86.333333    86.0
22  53       5     32      7    76   82       78  236  Pass  78.666667    79.0
23  54       5     27      5    51   78       60  189  Pass  63.000000    64.5
24  55       5     32      6    44   67       50  161  Fail  53.666667    55.5

In [9]:
import numpy as np
df = df.assign(retest = np.where(df['avg'] >= 60, 'No', 'Ok'))
print(df)

    no  nclass  hours  extra  math  eng  science  tot  test        avg  \
0   11       1     17      6    37   70       44  151  Pass  50.333333
1   12       1     30      7    60   80       70  210  Pass  70.000000
2   13       1     19      7    41   71       46  158  Pass  52.666667
3   14       1     14      4    34   67       40  141  Fail  47.000000
4   15       1     27      4    82   78       73  233  Pass  77.666667
5   21       2     13      4    34   67       38  139  Fail  46.333333
6   22       2     35      9    84   83       85  252  Pass  84.000000
7   23       2     21      7    45   70       49  164  Pass  54.666667
8   24       2     16      8    34   69       42  145  Fail  48.333333
9   25       2     31      8    43   69       45  157  Fail  52.333333
10  31       3     10      1    35   65       36  136  Fail  45.333333
11  32       3     15      8    35   68       41  144  Fail  48.000000
12  33       3     23      5    46   71       55  172  Pass  57.333333
13  34       3     11      5    34   66       37  137  Fail  45.666667
14  35       3     29      7    58   80       68  206  Pass  68.666667
15  41       4     25      5    49   75       59  183  Pass  61.000000
16  42       4      9      2    33   67       35  135  Fail  45.000000
17  43       4     24      6    48   74       58  180  Pass  60.000000
18  44       4     33      8    81   80       80  241  Pass  80.333333
19  45       4     38      8    83   78       97  258  Pass  86.000000
20  51       5     40      9    85   86       90  261  Pass  87.000000
21  52       5     39     10    87   85       87  259  Pass  86.333333
22  53       5     32      7    76   82       78  236  Pass  78.666667
23  54       5     27      5    51   78       60  189  Pass  63.000000
24  55       5     32      6    44   67       50  161  Fail  53.666667

    me_avg retest
0     53.5     Ok
1     70.0     No
2     56.0     Ok
3     50.5     Ok
4     80.0     No
5     50.5     Ok
6     83.5     No
7     57.5     Ok
8     51.5     Ok
9     56.0     Ok
10    50.0     Ok
11    51.5     Ok
12    58.5     Ok
13    50.0     Ok
14    69.0     No
15    62.0     No
16    50.0     Ok
17    61.0     No
18    80.5     No
19    80.5     No
20    85.5     No
21    86.0     No
22    79.0     No
23    64.5     No
24    55.5     Ok

### 집단(그룹)별 요약 통계, 통계 요약(Summary Statistics)

1. df.groupby('컬럼명') : 지정 컬럼을 기준으로 그룹핑(집단화)
    - df.groupby('nclass')
    - df.groupby('nclass').mean()

### 요약통계함수( sum(), count(), max(), min(), median(), std() )
2. df.agg('컬럼명', '요약통계함수') : 다중 집계(aggregation) 작업
    - df.agg(mean_math = ('math', 'mean'))
    - df.agg(mean_math = ('math', 'mean'), max_math = ('math', 'max'))

In [18]:
import pandas as pd
df = pd.read_csv('exam.csv', header=0)
# print(df)
# 숫자형으로 변환할 컬럼 목록 지정 (필요시 컬럼명 수정)
num_cols = ['math', 'eng', 'science', 'tot']
df[num_cols] = df[num_cols].apply(pd.to_numeric, errors='coerce')
print(df.dtypes)
print(df.groupby('nclass')[num_cols].mean()) # nclass별 평균 구하기
print(df.groupby('nclass')[num_cols].mean()['math']) # nclass별 math 평균 구하기
print(df.groupby('nclass')[num_cols].max()['math']) # nclass별 math 최대값 구하기

no         int64
nclass     int64
hours      int64
extra      int64
math       int64
eng        int64
science    int64
tot        int64
test         str
dtype: object
        math   eng  science    tot
nclass
1       50.8  73.2     54.6  178.6
2       48.0  71.6     51.8  171.4
3       41.6  70.0     47.4  159.0
4       58.8  74.8     65.8  199.4
5       68.6  79.6     73.0  221.2
nclass
1    50.8
2    48.0
3    41.6
4    58.8
5    68.6
Name: math, dtype: float64
nclass
1    82
2    84
3    58
4    83
5    87
Name: math, dtype: int64

In [19]:
print(df.groupby('nclass')[num_cols].agg(['mean', 'max'])) # nclass별 math 평균과 최대값 구하기

        math       eng     science        tot
        mean max  mean max    mean max   mean  max
nclass
1       50.8  82  73.2  80    54.6  73  178.6  233
2       48.0  84  71.6  83    51.8  85  171.4  252
3       41.6  58  70.0  80    47.4  68  159.0  206
4       58.8  83  74.8  80    65.8  97  199.4  258
5       68.6  87  79.6  86    73.0  90  221.2  261

In [21]:
print(df.groupby('nclass')[num_cols].agg(mean_math = ('math', 'mean'), max_math = ('math', 'max'))) # nclass별 math 평균과 최대값 구하기

        mean_math  max_math
nclass
1            50.8        82
2            48.0        84
3            41.6        58
4            58.8        83
5            68.6        87

In [22]:
print(df.groupby('nclass', as_index=False)[num_cols].agg(mean_math = ('math', 'mean'), max_math = ('math', 'max'))) # nclass별 math 평균과 최대값 구하기

   nclass  mean_math  max_math
0       1       50.8        82
1       2       48.0        84
2       3       41.6        58
3       4       58.8        83
4       5       68.6        87

### 계층적 집단(그룹)별 요약 통계, 통계 요약(Summary Statistics)
1. df.groupby( ['1차그룹컬럼명', '2차그룹컬럼명'] )
    - df.groupby( ['manufacturer', 'drv'] ) # 제조사별 구동방식별 그룹핑
    - df.groupby( ['manufacturer', 'drv'] ).mean()
    
### 요약통계함수( sum(), count(), max(), min(), median(), std() )
2. df.agg('컬럼명', '요약통계함수') : 다중 집계(aggregation) 작업
    - df.agg(mean_cty = ('cty', 'mean'))
    - df.agg(mean_cty = ('cty', 'mean'), max_cty = ('cty', 'max'))

In [1]:
import pandas as pd
df = pd.read_csv('mpg.csv', header=0)
print(df.head())

  manufacturer model  displ  year  cyl       trans drv  cty  hwy fl category
0         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
1         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
2         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
3         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
4         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [3]:
print(df.groupby(['manufacturer', 'drv']).mean(numeric_only=True)) # manufacturer와 drv별 평균 구하기

                     displ         year       cyl        cty        hwy
manufacturer drv
audi         4    2.681818  2003.909091  5.454545  16.818182  25.272727
             f    2.328571  2002.857143  4.857143  18.857143  28.285714
chevrolet    4    5.700000  2003.500000  8.000000  12.500000  16.250000
             f    3.000000  2004.400000  5.200000  18.800000  27.600000
             r    5.840000  2005.300000  8.000000  14.100000  21.300000
dodge        4    4.796154  2004.538462  7.615385  12.000000  16.076923
             f    3.390909  2003.090909  5.818182  15.818182  22.363636
ford         4    4.507692  2001.769231  7.076923  13.307692  17.153846
             r    4.566667  2003.500000  7.333333  14.750000  21.750000
honda        f    1.711111  2003.000000  4.000000  24.444444  32.555556
hyundai      f    2.428571  2004.142857  4.857143  18.642857  26.857143
jeep         4    4.575000  2005.750000  7.250000  13.500000  17.625000
land rover   4    4.300000  2003.500000  8.000000  11.500000  16.500000
lincoln      r    5.400000  2002.000000  8.000000  11.333333  17.000000
mercury      4    4.400000  2003.500000  7.000000  13.250000  18.000000
nissan       4    4.050000  2003.500000  6.500000  13.750000  18.000000
             f    2.922222  2004.000000  5.111111  20.000000  27.555556
pontiac      f    3.960000  2002.600000  6.400000  17.000000  26.400000
subaru       4    2.457143  2004.142857  4.000000  19.285714  25.571429
toyota       4    3.613333  2002.600000  5.733333  14.933333  18.800000
             f    2.431579  2002.789474  4.631579  21.368421  29.736842
volkswagen   f    2.255556  2002.666667  4.592593  20.925926  29.222222

In [6]:
print(df.groupby(['manufacturer', 'drv'])[[ 'cty', 'hwy']].mean(numeric_only=True)) # manufacturer와 drv별 평균 구하기

                        cty        hwy
manufacturer drv
audi         4    16.818182  25.272727
             f    18.857143  28.285714
chevrolet    4    12.500000  16.250000
             f    18.800000  27.600000
             r    14.100000  21.300000
dodge        4    12.000000  16.076923
             f    15.818182  22.363636
ford         4    13.307692  17.153846
             r    14.750000  21.750000
honda        f    24.444444  32.555556
hyundai      f    18.642857  26.857143
jeep         4    13.500000  17.625000
land rover   4    11.500000  16.500000
lincoln      r    11.333333  17.000000
mercury      4    13.250000  18.000000
nissan       4    13.750000  18.000000
             f    20.000000  27.555556
pontiac      f    17.000000  26.400000
subaru       4    19.285714  25.571429
toyota       4    14.933333  18.800000
             f    21.368421  29.736842
volkswagen   f    20.925926  29.222222

In [ ]:
# manufacturer와 drv별 cty 평균과 최대값 구하기
print(df.groupby(['manufacturer', 'drv']).agg(mean_cty=('cty', 'mean'), max_cty=('cty', 'max')))

                   mean_cty  max_cty
manufacturer drv
audi         4    16.818182       20
             f    18.857143       21
chevrolet    4    12.500000       14
             f    18.800000       22
             r    14.100000       16
dodge        4    12.000000       15
             f    15.818182       18
ford         4    13.307692       15
             r    14.750000       18
honda        f    24.444444       28
hyundai      f    18.642857       21
jeep         4    13.500000       17
land rover   4    11.500000       12
lincoln      r    11.333333       12
mercury      4    13.250000       14
nissan       4    13.750000       15
             f    20.000000       23
pontiac      f    17.000000       18
subaru       4    19.285714       21
toyota       4    14.933333       17
             f    21.368421       28
volkswagen   f    20.925926       35