### 통계 분석
1. 기술통계(Descriptive Statistics)
- 데이터를 요약해 설명하는 통계 분석 기법

2. 추론통계(Inferential Statistics)
- 단순히 숫자를 요약하는 것을 넘어, 어떤 값이 발생할 확률 계산

3. 예시 : 성별에 따라 급여 차이 분석
- 기술통계 분석 : 성별에 따른 평균 급여 계산으로 차이를 분석 (남성 100, 여성 93)
- 추론통계 분석 : 급여 차이가 유의미한 것인지 분석 (유의확률(p-value) : 우연히 나타날 확률로 판정)

4. 통계적 가설 검정 : 유의확률을 이용해 가설 검정하는 방법
- t-검정(t-test)
    - 유의확률 5%를 판단 기준(p-value < 0.05, 유의미)
- 상관관계(correlation)
    - 두 변수 사이에 관련성 분석(상관계수(0~1))

### 기술 통계 분석
[문제 1] 자동차 연비 데이터셋(mpg.csv)에서 자동차 종류가 compact, suv 자동차의 도시 연비(cty)를 분석하시오.

In [2]:
import pandas as pd
df = pd.read_csv('mpg.csv', header=0) # header=0은 첫 번째 행이 열 이름임을 나타냅니다.
df.head()

  manufacturer model  displ  year  cyl       trans drv  cty  hwy fl category
0         audi    a4    1.8  1999    4    auto(l5)   f   18   29  p  compact
1         audi    a4    1.8  1999    4  manual(m5)   f   21   29  p  compact
2         audi    a4    2.0  2008    4  manual(m6)   f   20   31  p  compact
3         audi    a4    2.0  2008    4    auto(av)   f   21   30  p  compact
4         audi    a4    2.8  1999    6    auto(l5)   f   16   26  p  compact

In [ ]:
# 조건 검색
from numpy import mean


df_stat = df.query('category in ["compact", "suv"]') # category 열에서 compact 또는 suv인 행을 선택하여 df_stat에 저장
df_stat

,manufacturer,model,displ,year,cyl,trans,drv,cty,hwy,fl,category
0,audi,a4,1.8,1999,4,auto(l5),f,18,29,p,compact
1,audi,a4,1.8,1999,4,manual(m5),f,21,29,p,compact
2,audi,a4,2.0,2008,4,manual(m6),f,20,31,p,compact
3,audi,a4,2.0,2008,4,auto(av),f,21,30,p,compact
4,audi,a4,2.8,1999,6,auto(l5),f,16,26,p,compact
...,...,...,...,...,...,...,...,...,...,...,...
216,volkswagen,jetta,2.0,2008,4,manual(m6),f,21,29,p,compact
217,volkswagen,jetta,2.5,2008,5,auto(s6),f,21,29,r,compact
218,volkswagen,jetta,2.5,2008,5,manual(m5),f,21,29,r,compact
219,volkswagen,jetta,2.8,1999,6,auto(l4),f,16,23,r,compact
220,volkswagen,jetta,2.8,1999,6,manual(m5),f,17,24,r,compact

In [7]:
df_stat = df.query('category in ["compact", "suv"]').groupby('category', as_index=False).agg({'category': 'count', 'cty': 'mean'}) # category 열에서 compact 또는 suv인 행을 선택하여 category별로 그룹화한 후, 각 그룹의 평균을 계산하여 df_stat에 저장
df_stat

   category       cty
0        47  20.12766
1        62  13.50000

In [10]:
df_stat = df.query('category in ["compact", "suv"]').groupby('category', as_index=False).agg(n=('category', 'count'), mean=('cty', 'mean')) # category 열에서 compact 또는 suv인 행을 선택하여 category별로 그룹화한 후, 각 그룹의 평균을 계산하여 df_stat에 저장
df_stat

  category   n      mean
0  compact  47  20.12766
1      suv  62  13.50000

### 추론 통계, t-검정, t-test

In [14]:
compact = df.query('category == "compact"')['cty'] # category 열에서 compact인 행을 선택하여 cty 열의 값을 compact에 저장
compact

0      18
1      21
2      20
3      21
4      16
5      18
6      18
7      18
8      16
9      20
10     19
11     15
12     17
13     17
14     15
141    21
142    19
169    20
170    20
171    19
172    20
186    21
187    21
188    21
189    22
190    18
191    18
192    18
193    24
194    24
195    26
196    28
197    26
207    21
208    19
209    21
210    22
211    17
212    33
213    21
214    19
215    22
216    21
217    21
218    21
219    16
220    17
Name: cty, dtype: int64

In [15]:
suv = df.query('category == "suv"')['cty'] # category 열에서 suv인 행을 선택하여 cty 열의 값을 suv에 저장
suv

18     14
19     11
20     14
21     13
22     12
       ..
176    15
177    16
178    14
198    11
199    13
Name: cty, Length: 62, dtype: int64

In [17]:
import scipy.stats as stats
t_statistic, p_value = stats.ttest_ind(compact, suv) # compact와 suv의 cty 열의 값을 사용하여 독립 표본 t-검정을 수행하여 t-통계량과 p-값을 계산하여 t_statistic과 p_value에 저장
print(f"t-통계량: {t_statistic}, p-값: {p_value}")

t-통계량: 11.917282584324107, p-값: 2.3909550904711557e-21

[문제 2] mpg.csv에서 일반 휘발유(regular)와 고급 휘발유(premium)의 도시 연비(cty)를 분석하시오.

In [18]:
df_stat2 = df.query('fl in ["r", "p"]').groupby('fl', as_index=False).agg(n=('fl', 'count'), mean=('cty', 'mean')) # fl 열에서 "r" 또는 "p"인 행을 선택하여 fl별로 그룹화한 후, 각 그룹의 평균을 계산하여 df_stat에 저장
df_stat2

  fl    n       mean
0  p   52  17.365385
1  r  168  16.738095

In [19]:
regular = df.query('fl == "r"')['cty'] # fl 열에서 "r"인 행을 선택하여 cty 열의 값을 regular에 저장
premium = df.query('fl == "p"')['cty'] # fl 열에서 "p"인 행을 선택하여 cty 열의 값을 premium에 저장
t_statistic2, p_value2 = stats.ttest_ind(regular, premium) # regular와 premium의 cty 열의 값을 사용하여 독립 표본 t-검정을 수행하여 t-통계량과 p-값을 계산하여 t_statistic2와 p_value2에 저장
print(f"t-통계량: {t_statistic2}, p-값: {p_value2}")

t-통계량: -1.066182514588919, p-값: 0.28752051088667

### 상관관계(correlation)
- 두 변수 사이에 관련성 분석(상관계수(0~1))
- 상관계수 0.7 이상 : 강한 양의 상관관계
- 상관계수 0.3 이상 : 약한 양의 상관관계
- 상관계수 0.3 미만 : 거의 상관관계 없음
- 상관계수 : 양수(정비례), 음수(반비례)

[문제 1] 미국 경제 데이터셋(economics.csv)에서 실업자 수(unemployment)와 개인소비지출(pce) 간에 상호 관련성이 있는지 분석
1. date : 날짜(연-월-일)
2. pce(Personal Consumption Expenditure) : 개인소비지출 물가지수
3. pop(POPulation, in thousands) : 인구(천명 단위)
4. psavert(Personal Saving Rate) : 개인저축율
5. uempmed(median duration of unemployment, in weeks) : 실업지속기간(주 단위)
6. unemployment(number of unemployed in thousands) : 실업자 수(천명 단위)

In [20]:
import pandas as pd
df = pd.read_csv('economics.csv', header=0) # header=0은 첫 번째 행이 열 이름임을 나타냅니다.
df.head()

         date    pce     pop  psavert  uempmed  unemploy
0  1967-07-01  507.4  198712     12.5      4.5      2944
1  1967-08-01  510.5  198911     12.5      4.7      2945
2  1967-09-01  516.3  199113     11.7      4.6      2958
3  1967-10-01  512.9  199311     12.5      4.9      3143
4  1967-11-01  518.1  199498     12.5      4.7      3066

In [ ]:
# pce와 unemploy 만 추출해서 확인
df1 =  df[['pce', 'unemploy']]
df1

         pce  unemploy
0      507.4      2944
1      510.5      2945
2      516.3      2958
3      512.9      3143
4      518.1      3066
..       ...       ...
569  12122.0      8688
570  12080.8      8979
571  12095.9      8705
572  12161.5      8575
573  12158.9      8549

[574 rows x 2 columns]

In [ ]:
# 피어슨 상관계수 계산
df1.corr(method='pearson') # df1의 pce와 unemploy 열의 상관계수를 계산하여 출력합니다. method='pearson'은 피어슨 상관계수를 사용하여 계산하도록 지정합니다.

            pce  unemploy
pce       1.000     0.614
unemploy  0.614     1.000

In [27]:
import scipy.stats as stats
corr1 = stats.pearsonr(df1['pce'], df1['unemploy']) # df1의 pce와 unemploy 열의 피어슨 상관계수와 p-값을 계산하여 출력합니다. stats.pearsonr 함수는 두 개의 배열을 입력으로 받아 피어슨 상관계수와 p-값을 반환합니다.
print(f"피어슨 상관계수: {corr1[0]}, p-값: {corr1[1]}")

피어슨 상관계수: 0.6139996891258622, p-값: 9.080244007032699e-61