In [1]:
import pandas as pd

data = {
    '상품명': ['노트북', '마우스', '키보드', '책상', '의자', '모니터'],
    '카테고리': ['전자제품', '전자제품', '전자제품', '가구', '가구', '전자제품'],
    '가격': [1200000, 30000, 80000, 250000, 150000, 350000],
    '판매수량': [5, 20, 12, 4, 8, 6]
}

df = pd.DataFrame(data)

df

   상품명  카테고리       가격  판매수량
0  노트북  전자제품  1200000     5
1  마우스  전자제품    30000    20
2  키보드  전자제품    80000    12
3   책상    가구   250000     4
4   의자    가구   150000     8
5  모니터  전자제품   350000     6

In [2]:
df['매출액'] = df['가격'] * df['판매수량']
df

   상품명  카테고리       가격  판매수량      매출액
0  노트북  전자제품  1200000     5  6000000
1  마우스  전자제품    30000    20   600000
2  키보드  전자제품    80000    12   960000
3   책상    가구   250000     4  1000000
4   의자    가구   150000     8  1200000
5  모니터  전자제품   350000     6  2100000

In [5]:
df_filtered = df[(df['매출액'] > 1000000) & (df['카테고리'] == '전자제품')]
df_filtered.sort_values(by='매출액', ascending=False)
df_filtered

   상품명  카테고리       가격  판매수량      매출액
0  노트북  전자제품  1200000     5  6000000
5  모니터  전자제품   350000     6  2100000

In [7]:
top3 = df.sort_values(by='매출액', ascending=False).head(3)
top3[['상품명', '매출액']]

   상품명      매출액
0  노트북  6000000
5  모니터  2100000
4   의자  1200000