In [1]:
import pandas as pd
import numpy as np

data = {
    '학생ID': [101, 102, 103, 104, 105, 106, 107, 108],
    '이름': ['김민수', '이지은', '박준호', '최서연',
            '정하늘', '강지훈', '윤서진', '한도윤'],
    'Python': [85, 92, np.nan, 78, 95, 70, np.nan, 88],
    'SQL': [90, np.nan, 75, 88, 92, np.nan, 85, 80]
}

df = pd.DataFrame(data)
df2 = df.copy()
df

   학생ID   이름  Python   SQL
0   101  김민수    85.0  90.0
1   102  이지은    92.0   NaN
2   103  박준호     NaN  75.0
3   104  최서연    78.0  88.0
4   105  정하늘    95.0  92.0
5   106  강지훈    70.0   NaN
6   107  윤서진     NaN  85.0
7   108  한도윤    88.0  80.0

#### Python과 SQL 과목에 결측치가 각각 몇 개 있는지 확인하세요

In [2]:
df2.isnull().sum()

학생ID      0
이름        0
Python    2
SQL       2
dtype: int64

#### 각 과목의 결측치를 해당 과목의 **중앙값(Median)** 으로 대체하세요.

In [4]:
cols = ['Python', 'SQL']
for col in cols:
    median_value = df2[col].median()
    df2[col] = df2[col].fillna(median_value)
    
df2

   학생ID   이름  Python   SQL
0   101  김민수    85.0  90.0
1   102  이지은    92.0  86.5
2   103  박준호    86.5  75.0
3   104  최서연    78.0  88.0
4   105  정하늘    95.0  92.0
5   106  강지훈    70.0  86.5
6   107  윤서진    86.5  85.0
7   108  한도윤    88.0  80.0

#### 결측치를 처리한 후 학생별 평균 점수를 계산하세요.

In [5]:
df2['평균'] = df2[['Python', 'SQL']].mean(axis=1)

In [6]:
result = df2.sort_values(by='평균', ascending=False )
result

   학생ID   이름  Python   SQL     평균
4   105  정하늘    95.0  92.0  93.50
1   102  이지은    92.0  86.5  89.25
0   101  김민수    85.0  90.0  87.50
6   107  윤서진    86.5  85.0  85.75
7   108  한도윤    88.0  80.0  84.00
3   104  최서연    78.0  88.0  83.00
2   103  박준호    86.5  75.0  80.75
5   106  강지훈    70.0  86.5  78.25

#### 최종 결과에는 이름, Python, SQL, 평균점수만 출력하세요.

In [8]:
print("=== 최종 분석 결과 ===")
result[['이름', 'Python', 'SQL', '평균']]

=== 최종 분석 결과 ===

    이름  Python   SQL     평균
4  정하늘    95.0  92.0  93.50
1  이지은    92.0  86.5  89.25
0  김민수    85.0  90.0  87.50
6  윤서진    86.5  85.0  85.75
7  한도윤    88.0  80.0  84.00
3  최서연    78.0  88.0  83.00
2  박준호    86.5  75.0  80.75
5  강지훈    70.0  86.5  78.25