In [16]:
import pandas as pd

products = pd.DataFrame({
    '제품ID': ['P001', 'P002', 'P003', 'P004', 'P005'],
    '제품명': ['노트북', '마우스', '키보드', '모니터', '웹캠'],
    '가격': [1200000, 30000, 80000, 350000, 90000]
})

sales = pd.DataFrame({
    '주문ID': ['O101', 'O102', 'O103', 'O104',
             'O105', 'O106', 'O107'],
    '제품ID': ['P001', 'P002', 'P001', 'P003',
             'P004', 'P002', 'P999'],
    '판매수량': [2, 5, 1, 3, 2, 10, 4]
})

In [17]:
products.head()

   제품ID  제품명       가격
0  P001  노트북  1200000
1  P002  마우스    30000
2  P003  키보드    80000
3  P004  모니터   350000
4  P005   웹캠    90000

In [18]:
sales.head()

   주문ID  제품ID  판매수량
0  O101  P001     2
1  O102  P002     5
2  O103  P001     1
3  O104  P003     3
4  O105  P004     2

1. 제품ID를 기준으로 두 DataFrame을 결합하세요.

In [19]:
df = pd.merge(sales, products, on='제품ID', how='left', validate='many_to_one', indicator=True)
df

   주문ID  제품ID  판매수량  제품명         가격     _merge
0  O101  P001     2  노트북  1200000.0       both
1  O102  P002     5  마우스    30000.0       both
2  O103  P001     1  노트북  1200000.0       both
3  O104  P003     3  키보드    80000.0       both
4  O105  P004     2  모니터   350000.0       both
5  O106  P002    10  마우스    30000.0       both
6  O107  P999     4  NaN        NaN  left_only

2. 제품 정보가 존재하지 않는 주문을 찾으세요.

In [20]:
df[df['제품명'].isnull()]

   주문ID  제품ID  판매수량  제품명  가격     _merge
6  O107  P999     4  NaN NaN  left_only

3. 정상 주문의 매출액을 계산하세요.

In [21]:
df_order = df[df['제품명'].notnull()]
df_order['매출액'] = df_order['판매수량'] * df_order['가격']
df_order

   주문ID  제품ID  판매수량  제품명         가격 _merge        매출액
0  O101  P001     2  노트북  1200000.0   both  2400000.0
1  O102  P002     5  마우스    30000.0   both   150000.0
2  O103  P001     1  노트북  1200000.0   both  1200000.0
3  O104  P003     3  키보드    80000.0   both   240000.0
4  O105  P004     2  모니터   350000.0   both   700000.0
5  O106  P002    10  마우스    30000.0   both   300000.0

4. 제품별 총판매수량과 총매출액을 계산하세요.

In [22]:
df_order.groupby('제품명')[['판매수량', '매출액']].sum()

     판매수량        매출액
제품명
노트북     3  3600000.0
마우스    15   450000.0
모니터     2   700000.0
키보드     3   240000.0

5. 매출액이 높은 순서대로 정렬하세요.

In [23]:
df_order.groupby('제품명')[['판매수량', '매출액']].sum().sort_values(by='매출액', ascending=False)

     판매수량        매출액
제품명
노트북     3  3600000.0
모니터     2   700000.0
마우스    15   450000.0
키보드     3   240000.0